### ISSUE TITLE
Persist titles across restart

### ISSUE THREAD

**Issue by InfernoZeus** [tpamula/webextension-window-titler#12]
Not sure it this is easily possible, but it would be great to be able to persist titles for each window, so that they are used again when restoring windows at FF start up. I use this extension to label different windows for different topics, and going through each window and retagging them is frustrating.

**Comment by tpamula** [comment]
That's a good idea. I'll look into it.

**Comment by InfernoZeus** [comment]
I also use Treestyletabs, which remembers the heirarchy across restarts, so presumably that also stores extra information about windows/tabs. Perhaps it might be useful for some inspiration?

**Comment by tpamula** [comment]
@InfernoZeus I'm happy to let you know that this feature has been added & published.
