### ISSUE TITLE
Support custom opening tag & closing tag

### ISSUE THREAD

**Issue by tpamula** [tpamula/webextension-window-titler#14]
Acceptance criteria:
- [ ] Custom opening and closing tags replace the existing hardcoded opening and closing tags ("[" and "]")
- [ ] User is able to define the opening and closing tag independently
- [ ] Lengths of the tags should be limited to 100 characters
- [ ] When the user modifies the tags (one or both) the changes are applied instantaneously
- [ ] There is a way to restore the default values for the tags
- [ ] Modification of the tags takes place in the addon options
- [ ] Changes are persisted

**Comment by orchee** [comment]
[Check PR -> ](https://github.com/tpamula/webextension-window-titler/pull/18)
