### ISSUE TITLE
Window title does not show up when untitled tab is focused

### ISSUE THREAD

**Issue by dftbaustin** [tpamula/webextension-window-titler#17]
When I add a title to a window, then click on a webpage without a `<title>` element, the window title doesn't display. To quickly demonstrate the issue:

1. Open a new window and add a title
2. Enter this URL into the address bar (including the comma): `data:text/html,`
3. Open a new tab and enter this URL: `data:text/html,%3Ctitle%3Ehello%3C%2Ftitle%3E`

If you switch between the two tabs in the window, step 2's tab **hides** the window title while step 3's tab **displays** the window title.

**Comment by tpamula** [comment]
Hi @dftbaustin 

I'm aware of this issue. This is not a Window Titler but a Firefox bug actually. See [this ticket on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1387425) for reference. Voting it up would be helpful in getting this fixed.

There's no workaround on the addon level short of overriding the new tab page and injecting HTML for pages without a title but this seems to be a bit of overkill.

On the user level there's a way to make new tabs display the window title: install an addon overriding the new tab such as [this one](https://addons.mozilla.org/en-GB/firefox/addon/new-tab-override/). Setting it to use "/" for URL in the new tab page makes it fall back to some internal blank new tab page but with the window title visible.

**Comment by tpamula** [comment]
Even though the Bugzilla ticket is still open this seems to be fixed in Firefox 73.
