### ISSUE TITLE
Suggestion: what is the current window title in popup.

### ISSUE THREAD

**Issue by orchee** [tpamula/webextension-window-titler#20]
I'm thinking about providing information what is the current window title when user opens add-on popup. It can use placeholder property of the input. So whenever user opens popup he can immediately see what is the current title. Here you've got a mockup:
![obraz](https://user-images.githubusercontent.com/19973688/60000877-64e36c00-9665-11e9-8464-ab134ab8308b.png)

**Comment by tpamula** [comment]
Sure. Preferably it should be displayed as a preselected input text so it's intuitive and easy to modify for the user, not as a placeholder.
