### ISSUE TITLE
Suggestion: direct link to settings page from popup

### ISSUE THREAD

**Issue by orchee** [tpamula/webextension-window-titler#21]
As settings page becomes more useful, I'm suggesting to add direct link from popup. The only work to be done is adding button with event listener and running => browser.runtime.openOptionsPage()

[Mozilla docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/openOptionsPage)

**Comment by tpamula** [comment]
Cool. A new cog icon (emoji) can be added for that case and it could potentially replace the current info icon to keep the interface simple. Let's see how it plays out.

**Comment by orchee** [comment]
How this emoji looks on default Linux font? ⚙ It looks hideous on Windows :/
![obraz](https://user-images.githubusercontent.com/19973688/60016370-4e014180-9686-11e9-9ffc-31edf81bce76.png)

**Comment by orchee** [comment]
It looks better without Segoe UI loaded 🤦‍♂ 

![obraz](https://user-images.githubusercontent.com/19973688/60016533-ca942000-9686-11e9-9a3c-0ae4860e89ab.png)
