### ISSUE TITLE
FR: Please allow specify some format string for set title

### ISSUE THREAD

**Issue by Hubbitus** [tpamula/webextension-window-titler#27]
Some variables, placeholders, not just start and end tags.

My intention really place title at end of window title instead of front, but I think format specification may be more flexible.

**Comment by tpamula** [comment]
Hello, @Hubbitus. What kind of variables/placeholders do you have in mind? Could you provide some examples of how that would work, what issues would that solve?

**Comment by Hubbitus** [comment]
I mean something like: `<{tabTitle}> [{windowTitle}]`
And `{tabTitle}` and `{windowTitle}` should be expanded by real values.

**Comment by tpamula** [comment]
This could be done, but the current Firefox API doesn't support such changes directly and the way around that would be to directly modify the title of a web page. It would require additional permissions, could bring some issues (e.g. title changing dynamically, loads of tabs opened, sleeping tabs, default bookmark title would include the _window title_). Although it might be useful, maybe it's better to keep this addon simple and reliable and put this feature on hold.

**Comment by Hubbitus** [comment]
How API different on add prefix and replace whole text of window title?

**Comment by tpamula** [comment]
There's a parameter on windows.update() API method method called _titlePreface_ ([see here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/update)). Window Titler uses it to achieve its current functionality and there's no such equivalent for more extensive modifications of the browser's title. I took a peek at implementations of plugins that rename the tab title and what they do is they access the DOM's document node and modify the title from there ([here for example](https://github.com/Lazyuki/ReTitle/blob/master/js/background.js)).

These are two different approaches and while the latter has greater capabilities in terms of extended presentation customisability, it comes at the price of introducing a host of problems.

**Comment by tpamula** [comment]
There's a parameter on windows.update() API method method called _titlePreface_ ([see here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/update)). Window Titler uses it to achieve its current functionality and to the best to my knowledge there's no such equivalent for more extensive modifications of the browser's title aside from modifying the website title via script injection.

These are two different approaches and while the latter has greater capabilities in terms of extended presentation customisability, it comes at the price of introducing a host of problems.

**Comment by tpamula** [comment]
There's a parameter on windows.update() API method method called _titlePreface_ ([see here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/update)). Window Titler uses it to achieve its current functionality and to the best to my knowledge there's no such equivalent for more extensive modifications of the browser's title aside from modifying website titles via script injection.

These are two different approaches and while the latter has greater capabilities in terms of extended presentation customisability, it comes at the price of introducing a host of problems.

**Comment by tpamula** [comment]
There's a parameter on windows.update() API method method called _titlePreface_ ([see here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/update)). Window Titler uses it to achieve its current functionality and to the best to my knowledge there's no such equivalent for more extensive modifications of the browser's title aside from modifying websites' titles via script injection.

These are two different approaches and while the latter offers greater capabilities, it comes at the price of introducing a host of problems, at least when it comes to using the user window title as a suffix or any other customisation that is not a prefix.

**Comment by Hubbitus** [comment]
Sad to heard. But I understand. Thank you.
