### ISSUE TITLE
ADD option to tag each new window with unique hash

### ISSUE THREAD

**Issue by allanlaal** [tpamula/webextension-window-titler#28]
this would enable us to use different tools that use wmctrl to identify windows by tags, like wm-win-tool to restore Firefox to its correct workspace

**Comment by tpamula** [comment]
Hi Allan, 

Looks like the issue that wm-win-tool tackles was fixed in Firefox 75 [link](https://bugzilla.mozilla.org/show_bug.cgi?id=372650).

**Comment by tpamula** [comment]
Hi Allan, 

Looks like the issue that wm-win-tool tackles was fixed in Firefox 75 [link](https://bugzilla.mozilla.org/show_bug.cgi?id=372650). If that's the case the integration doesn't won't be necessary, we just have to wait for the Firefox 75 to be released.

**Comment by tpamula** [comment]
Hi Allan, 

Looks like the issue that wm-win-tool tackles was fixed in Firefox 75 [link](https://bugzilla.mozilla.org/show_bug.cgi?id=372650). If that's the case the integration won't be necessary, we just have to wait for the Firefox 75 to be released.

**Comment by frispete** [comment]
Yeah, given the long history of this issue, I believe in this only after extensive testing..
