### ISSUE TITLE
add packaging and installation instructions to readme file

### ISSUE THREAD

**Issue by weiss-gal** [tpamula/webextension-window-titler#64]
It might be trivial, but is it possible to add instructions of how to take the code, package it as xpi and install on firefox ?

**Comment by tpamula** [comment]
Hello @weiss-gal 

Good idea. It used to work with `npm run start` back during the development, but, as I checked, it stopped since. This is now addresed and the up-to-date instruction is present now in CONTRIBUTING.md

Actually maybe I ought to look into some updates for this project.

**Comment by weiss-gal** [comment]
10x, just went through the instructions and successfully installed it on latest firefox developer edition (113.0b3)
